name: "Debian"

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build"
    steps:
      - run: echo "PKG_NAME=$( echo '${{ github.repository }}' | awk -F 'debian-' '{print $2}' )" >> $GITHUB_ENV
        shell: bash
      - uses: ghastore/unixstore-debian-build@main
        with:
          git_repo_src: "https://github.com/${{ github.repository }}.git"
          git_repo_dst: "https://github.com/unixstore-debian/${{ env.PKG_NAME }}.git"
          git_user: "${{ secrets.BOT_GITHUB_NAME }}"
          git_email: "${{ secrets.BOT_GITHUB_EMAIL }}"
          git_token: "${{ secrets.BOT_GITHUB_TOKEN }}"
          obs_user: "${{ secrets.OBS_USER }}"
          obs_password: "${{ secrets.OBS_PASSWORD }}"
          obs_token: "${{ secrets.OBS_TOKEN }}"
          obs_project: "home:unixstore:debian"
          obs_package: "${{ env.PKG_NAME }}"
