name: "Repository"

on:
  - push

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: "Mirror"
    steps:
      - uses: ghastore/mirror@main
        with:
          src_repo: "https://github.com/${{ github.repository }}.git"
          src_user: "${{ secrets.BOT_GITHUB_NAME }}"
          src_token: "${{ secrets.BOT_GITHUB_TOKEN }}"
          dst_repo: "https://gitlab.com/${{ github.repository }}.git"
          dst_user: "${{ secrets.BOT_GITLAB_NAME }}"
          dst_token: "${{ secrets.BOT_GITLAB_TOKEN }}"
